[tool.poetry]
name = "projectrcj"
version = "0.1.0"
description = "A description of what your project does"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
